done: {condition: AMB, iteration: 0, trial: 0}
params:
  AMB: {num_iterations: 3, num_trials: 2}
  FGB: {num_iterations: 3, num_trials: 2}
  OPT: {num_iterations: 3, num_trials: 2}
  RMB: {num_iterations: 3, num_trials: 2}
  RmB: {num_iterations: 3, num_trials: 2}
  SG: {num_iterations: 3, num_trials: 2}
sequence: [AMB, RMB, RmB, FGB, SG, OPT]
